#!/usr/bin/env node
// Builds ONE self-contained HTML file (no external requests) for Google Apps Script, Canvas, or any web host.
// Usage: node build.js
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const JS_ORDER = [
  'data.js', 'seal.js', 'formula.js', 'engine.js', 'workbook.js', 'mldata.js', 'sql.js', 'platforms.js', 'csv.js', 'wrangle.js', 'certtest.js',
  '@TESTBANK', 'challenges.js', 'lessons.js', 'reference.js', 'ui-core.js', 'ui-sheet.js', 'ui-csv.js', 'ui-sql.js', 'ui-wrangle.js', 'ui-cert.js',
  'ui-reference.js', 'ui-rdbms.js', 'ui-ml.js', 'ui-test.js', 'main.js'
];

// Certification-test question banks: run every reference answer through the real engine, ship only answer fingerprints.
const SX = require('./tests/load.js')(['certtest.js']);
const built = require('./src/banks/build-bank.js')(SX, require('./src/banks/questions.js'));
if (built.problems.length) { console.error(built.problems.join('\n')); throw new Error('Question bank has problems — fix them before building.'); }
const bankJson = JSON.stringify(built.bank);
if (/"(a|ref|fields)":/.test(bankJson)) throw new Error('Answers leaked into the shipped question bank!');
const bankJs = '(function (SX) {\n  \'use strict\';\n  // Generated by build.js from src/banks/questions.js — fingerprints only, no answers.\n  SX.TESTBANK = ' + bankJson + ';\n})(globalThis.SX = globalThis.SX || {});\n';

const css = fs.readFileSync(path.join(SRC, 'css', 'styles.css'), 'utf8');
const js = JS_ORDER.map((f) => '// ---- ' + f + ' ----\n' + (f === '@TESTBANK' ? bankJs : fs.readFileSync(path.join(SRC, 'js', f), 'utf8'))).join('\n');
if (/<\/script/i.test(js)) throw new Error('A source file contains "</script" which would break the inline build.');

const template = fs.readFileSync(path.join(SRC, 'index.html'), 'utf8');
const html = template.replace('/*INLINE_CSS*/', () => css).replace('/*INLINE_JS*/', () => js);
if (html.split('__SX_CLASS_KEY__').length !== 2) throw new Error('The class-key marker must appear exactly once (Code.gs replaces it).');

fs.mkdirSync(path.join(__dirname, 'dist'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'dist', 'index.html'), html);
fs.writeFileSync(path.join(__dirname, 'apps-script', 'Index.html'), html);
const nq = Object.values(built.bank).reduce((a, b) => a + b.length, 0);
console.log('Built dist/index.html and apps-script/Index.html (' + Math.round(html.length / 1024) + ' KB; ' + nq + ' certification-test questions)');
