// SheetEX — certification-test question banks. This file holds the answers and is never shipped in the app: The build runs every reference answer through the real engine (src/js/certtest.js), stores only a
// fingerprint of the result in the student app, and fails if a reference answer errors or could be faked.
//
// kinds: mc (a = correct option) · text (a = accepted answers) · formula (ref = a correct formula; any formula with
// the same results on the original AND a shuffled copy of the data is accepted) · sql (ref query; any query with the
// same rows is accepted) · probe (ref SQL; hidden probe statements must succeed/fail the same way) · csv (fields).
'use strict';

const P = { sheet: 'Products', cols: 'A:H', rows: 4, last: 25 };
const S = { sheet: 'Sales', cols: 'A:F', rows: 4, last: 61 };
const ST = { sheet: 'Stores', cols: 'A:F', rows: 5, last: 6 };
const RAW = { sheet: 'RawOrders', cols: 'A:H', rows: 5, last: 31 };
const T = { sheet: 'Targets', cols: 'A:F', rows: 4, last: 4 };
const CT = { sheet: 'Contacts', cols: 'A:F', rows: 4, last: 9 };
const IC = { sheet: 'ItemCodes', cols: 'A:D', rows: 3, last: 25 };

module.exports = {
  xl365: [
    { id: 'x1-sum', kind: 'formula', topic: 'SUM', plat: 'xl365', at: 'B2', show: [P], ref: '=SUM(Products!F2:F25)',
      q: 'Write a formula for the <b>total number of units in stock</b> across all products (InStock is column F, rows 2–25).' },
    { id: 'x1-countif', kind: 'formula', topic: 'COUNTIF', plat: 'xl365', at: 'B2', show: [P], ref: '=COUNTIF(Products!D2:D25,">10")',
      q: 'Write a formula that counts how many products have a <b>Price greater than $10</b>.' },
    { id: 'x1-sumif', kind: 'formula', topic: 'SUMIF', plat: 'xl365', at: 'B2', show: [S], ref: '=SUMIF(Sales!C2:C61,"S02",Sales!E2:E61)',
      q: 'Write a formula for the <b>total Qty sold by store S02</b> (Sales rows 2–61).' },
    { id: 'x1-avgif', kind: 'formula', topic: 'AVERAGEIF', plat: 'xl365', at: 'B2', show: [P], ref: '=AVERAGEIF(Products!C2:C25,"Snacks",Products!D2:D25)',
      q: 'Write a formula for the <b>average Price of the Snacks</b> category.' },
    { id: 'x1-xlookup', kind: 'formula', topic: 'XLOOKUP', plat: 'xl365', at: 'B2', show: [P], ref: '=XLOOKUP("SKU-404",Products!A2:A25,Products!D2:D25)',
      q: 'Write a lookup formula that returns the <b>Price of SKU-404</b>. (It must keep working if rows are re-sorted.)' },
    { id: 'x1-filter', kind: 'formula', topic: 'FILTER', plat: 'xl365', at: 'B2', show: [P], ref: '=FILTER(Products!B2:B25,Products!C2:C25="Apparel")',
      q: 'Write ONE formula that spills the <b>names of every Apparel product</b>, in the order they appear in the table.' },
    { id: 'x1-sortunique', kind: 'formula', topic: 'SORT + UNIQUE', plat: 'xl365', at: 'B2', show: [P], ref: '=SORT(UNIQUE(Products!C2:C25))',
      q: 'Write ONE formula that spills an <b>A→Z list of the categories, each listed once</b>.' },
    { id: 'x1-value', kind: 'formula', topic: 'Relative references', plat: 'xl365', sheet: 'Products', at: 'J2', fill: 25, show: [P], ref: '=D2*F2',
      q: 'In <b>Products!J2</b>, write a formula for that product\'s <b>inventory value (Price × InStock)</b>. It will be filled down to row 25.' },
    { id: 'x1-if', kind: 'formula', topic: 'IF', plat: 'xl365', sheet: 'Products', at: 'J2', fill: 25, show: [P], ref: '=IF(F2<G2,"Reorder","OK")',
      q: 'In <b>Products!J2</b>, write a formula that shows <b>"Reorder"</b> when InStock is below ReorderAt, otherwise <b>"OK"</b>. It will be filled down to row 25.' },
    { id: 'x1-spill', kind: 'mc', topic: '#SPILL!', q: 'A FILTER formula shows <code>#SPILL!</code>. What is the most likely cause?',
      opts: ['Cells below or beside it are not empty', 'The formula has a typo in the function name', 'No rows matched the condition', 'The range is too small'], a: 'Cells below or beside it are not empty' },
    { id: 'x1-abs', kind: 'mc', topic: 'Absolute references', q: 'Cell K2 holds <code>=E2*$H$1</code>. You fill it down to K3. What does K3 hold?',
      opts: ['=E3*$H$1', '=E3*$H$2', '=E2*$H$1', '=F2*$H$1'], a: '=E3*$H$1' },
    { id: 'x1-len', kind: 'text', topic: 'Text functions', q: 'What does <code>=LEN("Peachtree")</code> return?', a: ['9'] },
    { id: 'x1-round', kind: 'text', topic: 'ROUND', q: 'What does <code>=ROUND(12.4867, 2)</code> return?', a: ['12.49'] },
    { id: 'x1-dyn', kind: 'mc', topic: 'Dynamic arrays', q: 'Which of these functions returns a list of results that <b>spills</b> into the cells below?',
      opts: ['UNIQUE', 'COUNTIF', 'VLOOKUP', 'ROUND'], a: 'UNIQUE' },
    { id: 'x1-why', kind: 'mc', topic: 'Formulas vs typed values', q: 'Why is <code>=SUM(F2:F25)</code> better than typing the total (1,357) into the cell?',
      opts: ['It updates when the data changes', 'It makes the file smaller', 'Typed numbers cannot be formatted', 'Excel cannot add typed numbers'], a: 'It updates when the data changes' },
    { id: 'x1-filldown', kind: 'mc', topic: 'Fill down', q: 'You select J2:J25 (J2 has a formula) and press <kbd>Ctrl</kbd>+<kbd>D</kbd>. What happens?',
      opts: ['J2 is copied into J3:J25, with references shifted row by row', 'J2 is deleted', 'The column is sorted', 'J3:J25 get the exact same formula with no changes'], a: 'J2 is copied into J3:J25, with references shifted row by row' }
  ],

  xl2013: [
    { id: 'x2-indexmatch', kind: 'formula', topic: 'INDEX + MATCH', plat: 'xl2013', at: 'B2', show: [P], ref: '=INDEX(Products!D2:D25,MATCH("SKU-404",Products!A2:A25,0))',
      q: 'This workbook is opened in <b>Excel 2013</b>. Write a formula that returns the <b>Price of SKU-404</b>.' },
    { id: 'x2-vlookup', kind: 'formula', topic: 'VLOOKUP', plat: 'xl2013', at: 'B2', show: [P], ref: '=VLOOKUP("SKU-203",Products!A2:H25,2,FALSE)',
      q: 'In Excel 2013, write a formula that returns the <b>Product name for SKU-203</b>.' },
    { id: 'x2-nestedif', kind: 'formula', topic: 'Nested IF', plat: 'xl2013', sheet: 'Products', at: 'J2', fill: 25, show: [P], ref: '=IF(F2<G2,"Reorder",IF(F2<G2*1.5,"Low","OK"))',
      q: 'Excel 2013 has no IFS. In <b>Products!J2</b>, show <b>"Reorder"</b> if InStock &lt; ReorderAt, <b>"Low"</b> if InStock &lt; 1.5 × ReorderAt, otherwise <b>"OK"</b>. It will be filled down to row 25.' },
    { id: 'x2-cse', kind: 'formula', topic: 'Array formulas (CSE)', plat: 'xl2013', at: 'B2', show: [S], cse: true, ref: '=MAX(IF(Sales!C2:C61="S03",Sales!E2:E61))',
      q: 'Excel 2013 has no MAXIFS. Write a formula for the <b>largest single-order Qty sold by store S03</b>.' },
    { id: 'x2-sumproduct', kind: 'formula', topic: 'SUMPRODUCT', plat: 'xl2013', at: 'B2', show: [P], ref: '=SUMPRODUCT(Products!D2:D25,Products!F2:F25)',
      q: 'In ONE cell, write a formula for the <b>total inventory value</b>: the sum of Price × InStock over every product.' },
    { id: 'x2-countif', kind: 'formula', topic: 'COUNTIF', plat: 'xl2013', at: 'B2', show: [S], ref: '=COUNTIF(Sales!E2:E61,">=5")',
      q: 'Write a formula that counts the orders with a <b>Qty of 5 or more</b>.' },
    { id: 'x2-join', kind: 'formula', topic: 'Joining text', plat: 'xl2013', sheet: 'Stores', at: 'G2', fill: 6, show: [ST], ref: '=B2&", "&C2',
      q: 'In <b>Stores!G2</b> (Excel 2013), join City and State like <b>Cumming, GA</b>. It will be filled down to row 6.' },
    { id: 'x2-name', kind: 'mc', topic: '#NAME?', q: 'What does Excel 2013 show for <code>=XLOOKUP("SKU-101",A2:A25,B2:B25)</code>?',
      opts: ['#NAME?', '#N/A', '#VALUE!', 'Granola Bar'], a: '#NAME?' },
    { id: 'x2-csekey', kind: 'mc', topic: 'Array formulas (CSE)', q: 'How do you enter an array formula like <code>{=MAX(IF(…))}</code> in Excel 2013?',
      opts: ['Press Ctrl+Shift+Enter', 'Type the curly braces yourself', 'Press Enter twice', 'Wrap it in ARRAYFORMULA()'], a: 'Press Ctrl+Shift+Enter' },
    { id: 'x2-false', kind: 'mc', topic: 'VLOOKUP', q: 'In <code>=VLOOKUP("SKU-203", A2:H25, 2, FALSE)</code>, what does <code>FALSE</code> mean?',
      opts: ['Find an exact match only', 'Return the 2nd match', 'Search from the bottom up', 'Ignore capital letters'], a: 'Find an exact match only' },
    { id: 'x2-approx', kind: 'mc', topic: 'VLOOKUP', q: 'Someone leaves off the last argument of VLOOKUP on an <b>unsorted</b> list. What happens?',
      opts: ['It does an approximate match and can quietly return the wrong row', 'It always returns #N/A', 'Excel refuses the formula', 'It works exactly the same as FALSE'], a: 'It does an approximate match and can quietly return the wrong row' },
    { id: 'x2-match', kind: 'text', topic: 'MATCH', q: 'Products!A2:A25 starts SKU-101, SKU-102, SKU-103… What does <code>=MATCH("SKU-103",Products!A2:A25,0)</code> return?', a: ['3'] },
    { id: 'x2-implicit', kind: 'mc', topic: 'Array formulas (CSE)', q: 'In Excel 2013, <code>=MAX(IF(C2:C61="S03",E2:E61))</code> is entered with plain Enter. What happens?',
      opts: ['It does not look at the whole range: it uses one row (or shows #VALUE!), so the answer is wrong', 'It works the same as Ctrl+Shift+Enter', 'It shows #SPILL!', 'Excel converts it to MAXIFS'], a: 'It does not look at the whole range: it uses one row (or shows #VALUE!), so the answer is wrong' },
    { id: 'x2-exists', kind: 'mc', topic: 'Version differences', q: 'Which function exists in Excel 2013?',
      opts: ['IFERROR', 'IFS', 'TEXTJOIN', 'XLOOKUP'], a: 'IFERROR' },
    { id: 'x2-iferror', kind: 'mc', topic: 'IFERROR', q: 'What does <code>=IFERROR(VLOOKUP("SKU-999",A2:D25,4,FALSE),"Not found")</code> show when SKU-999 is not in the list?',
      opts: ['Not found', '#N/A', '0', 'FALSE'], a: 'Not found' }
  ],

  gs: [
    { id: 'g-filter', kind: 'formula', topic: 'FILTER', plat: 'gs', at: 'B2', show: [P], ref: '=FILTER(Products!B2:B25,Products!C2:C25="Drinks")',
      q: 'In <b>Google Sheets</b>, write ONE formula that lists the <b>names of all Drinks products</b>.' },
    { id: 'g-sort', kind: 'formula', topic: 'SORT', plat: 'gs', at: 'B2', show: [P], ref: '=SORT(Products!B2:D25,3,FALSE)',
      q: 'In Google Sheets, sort the block <b>Products!B2:D25</b> by Price (its 3rd column), <b>highest price first</b>.' },
    { id: 'g-arrayformula', kind: 'formula', topic: 'ARRAYFORMULA', plat: 'gs', at: 'B2', show: [P], ref: '=ARRAYFORMULA(Products!D2:D25*Products!F2:F25)',
      q: 'In ONE cell, write a Google Sheets formula that fills a whole column with <b>Price × InStock for every product</b> (rows 2–25).' },
    { id: 'g-query', kind: 'formula', topic: 'QUERY', plat: 'gs', at: 'B2', show: [P], ref: '=QUERY(Products!A1:H25,"select B where C = \'Snacks\'",1)',
      q: 'Use <b>QUERY</b> on Products!A1:H25 (1 header row) to list the Product names in the <b>Snacks</b> category, with the header <b>Product</b> on top.' },
    { id: 'g-split', kind: 'formula', topic: 'SPLIT', plat: 'gs', sheet: 'Products', at: 'J2', fill: 25, show: [P], ref: '=SPLIT(H2," ")',
      q: 'In <b>Products!J2</b>, split the Supplier name into <b>one word per cell</b> (spilling to the right). It will be filled down to row 25.' },
    { id: 'g-regex', kind: 'formula', topic: 'REGEXMATCH', plat: 'gs', at: 'B2', show: [P], ref: '=SUMPRODUCT(--REGEXMATCH(Products!B2:B25,"[0-9]"))',
      q: 'Write a Google Sheets formula that counts how many <b>product names contain a digit</b> (0–9).' },
    { id: 'g-concat', kind: 'formula', topic: 'Joining text', plat: 'gs', sheet: 'Stores', at: 'G2', fill: 6, show: [ST], ref: '=B2&", "&C2',
      q: 'In <b>Stores!G2</b> (Google Sheets), join City and State like <b>Cumming, GA</b>. It will be filled down to row 6.' },
    { id: 'g-sortneg', kind: 'mc', topic: 'Silent differences', q: 'In Google Sheets, <code>=SORT(A2:B25, 2, -1)</code> sorts column 2…',
      opts: ['Lowest to highest — -1 counts as TRUE (ascending)', 'Highest to lowest', 'It shows #ERROR!', 'It does not sort at all'], a: 'Lowest to highest — -1 counts as TRUE (ascending)' },
    { id: 'g-error', kind: 'mc', topic: 'Errors', q: 'You type a formula with a missing quote mark. What does Google Sheets do?',
      opts: ['Accepts it and shows #ERROR! in the cell', 'Shows a pop-up and refuses to enter it', 'Fixes the quote for you', 'Shows #NAME?'], a: 'Accepts it and shows #ERROR! in the cell' },
    { id: 'g-open', kind: 'mc', topic: 'Open-ended ranges', q: 'What does <code>E2:E</code> mean in Google Sheets?',
      opts: ['Column E from row 2 down to the last row', 'Only cell E2', 'Columns E through Z', 'It is an error'], a: 'Column E from row 2 down to the last row' },
    { id: 'g-concat2', kind: 'mc', topic: 'Joining text', q: 'How many values can Google Sheets\' <code>CONCAT</code> join?',
      opts: ['Exactly 2', 'Any number', 'Up to 30', 'Only ranges'], a: 'Exactly 2' },
    { id: 'g-filterargs', kind: 'mc', topic: 'FILTER', q: 'In Google Sheets, <code>=FILTER(B2:B25, C2:C25="Snacks", D2:D25&gt;1)</code> — what is the third argument?',
      opts: ['A second condition (both must be true)', 'What to show if nothing matches', 'The sort order', 'The number of results'], a: 'A second condition (both must be true)' },
    { id: 'g-split3', kind: 'text', topic: 'SPLIT', q: 'Into how many cells does <code>=SPLIT("snacks|drinks|apparel", "|")</code> spill?', a: ['3', 'three'] },
    { id: 'g-af', kind: 'mc', topic: 'ARRAYFORMULA', q: 'What is ARRAYFORMULA for?',
      opts: ['Making one formula work on whole ranges so it fills a column', 'Entering formulas with Ctrl+Shift+Enter', 'Sorting arrays', 'Importing data from another file'], a: 'Making one formula work on whole ranges so it fills a column' },
    { id: 'g-query-lang', kind: 'mc', topic: 'QUERY', q: 'In <code>=QUERY(A1:H25, "select B where C = \'Snacks\'", 1)</code>, what are B and C?',
      opts: ['Column letters of the range', 'Named ranges', 'Sheet names', 'Cell values'], a: 'Column letters of the range' }
  ],

  csv: [
    { id: 'c-comma', kind: 'csv', topic: 'Quoting commas', fields: [['SKU-302', 'Gel Pens, 4-pack', '4.5']], ref: 'SKU-302,"Gel Pens, 4-pack",4.5',
      q: 'Write the <b>CSV line</b> for this row — SKU: <code>SKU-302</code> · Product: <code>Gel Pens, 4-pack</code> · Price: <code>4.5</code>' },
    { id: 'c-quote', kind: 'csv', topic: 'Escaping quotes', fields: [['SKU-307', '12" Ruler', '1.99']], ref: 'SKU-307,"12"" Ruler",1.99',
      q: 'Write the <b>CSV line</b> for — SKU: <code>SKU-307</code> · Product: <code>12" Ruler</code> · Price: <code>1.99</code>' },
    { id: 'c-blank', kind: 'csv', topic: 'Empty fields', fields: [['SKU-999', '', '2.5']], ref: 'SKU-999,,2.5',
      q: 'Write the <b>CSV line</b> for a row whose middle value is <b>missing</b> — SKU: <code>SKU-999</code> · Product: <i>(empty)</i> · Price: <code>2.5</code>' },
    { id: 'c-tsv', kind: 'csv', delim: '\t', topic: 'TSV', fields: [['Gel Pens, 4-pack', '4.5']], ref: 'Gel Pens, 4-pack\t4.5',
      q: 'Write the <b>TSV</b> (tab-separated) line for — Product: <code>Gel Pens, 4-pack</code> · Price: <code>4.5</code>. (Press Tab in the answer box to type a tab.)' },
    { id: 'c-two', kind: 'csv', topic: 'Quoting commas', fields: [['Name', 'Note'], ['Avery', 'Said "hi", then left']], ref: 'Name,Note\nAvery,"Said ""hi"", then left"',
      q: 'Write a 2-line CSV file: a header row <code>Name</code>, <code>Note</code> and one data row — Name: <code>Avery</code> · Note: <code>Said "hi", then left</code>' },
    { id: 'c-zip', kind: 'csv', topic: 'Leading zeros', fields: [['Burlington', 'VT', '05401']], ref: 'Burlington,VT,05401',
      q: 'Write the <b>CSV line</b> for — City: <code>Burlington</code> · State: <code>VT</code> · Zip: <code>05401</code> (keep the zero!)' },
    { id: 'c-formulas', kind: 'mc', topic: 'Values vs formulas', q: 'A sheet with <code>=SUM(D2:D25)</code> in D26 is saved as CSV. What is stored in that spot?',
      opts: ['Only the result, like 233.12', 'The formula =SUM(D2:D25)', 'Both the formula and the result', 'Nothing — CSV skips formula cells'], a: 'Only the result, like 233.12' },
    { id: 'c-zero', kind: 'mc', topic: 'Leading zeros', q: 'A CSV holds the Zip <code>05401</code>. You open it by double-clicking in Excel. What do you see?',
      opts: ['5401', '05401', '#VALUE!', '5,401.00'], a: '5401' },
    { id: 'c-long', kind: 'mc', topic: 'Long numbers', q: 'A CSV has a 16-digit ID <code>4111222233334444</code>. After opening and saving in Excel it becomes…',
      opts: ['4111222233334440 (Excel keeps only 15 digits)', 'Exactly the same', '#NUM!', 'The text "4111222233334444"'], a: '4111222233334440 (Excel keeps only 15 digits)' },
    { id: 'c-delim', kind: 'mc', topic: 'Delimiters', q: 'What separates the values in a TSV file?',
      opts: ['A tab character', 'A comma', 'A semicolon', 'A space'], a: 'A tab character' },
    { id: 'c-count', kind: 'text', topic: 'Quoting commas', q: 'How many fields are in this CSV line?  <code>a,"b,c",d</code>', a: ['3', 'three'] },
    { id: 'c-lost', kind: 'mc', topic: 'Values vs formulas', q: 'Which of these does a CSV file keep?',
      opts: ['The values in one sheet', 'Bold text and colors', 'Several sheets', 'Formulas'], a: 'The values in one sheet' },
    { id: 'c-dq', kind: 'text', topic: 'Escaping quotes', q: 'Inside a quoted CSV value, how do you write ONE quote mark character? Type exactly what goes in the file.', a: ['""'] },
    { id: 'c-date', kind: 'mc', topic: 'Import surprises', q: 'A CSV contains the code <code>1-2</code> (aisle 1, shelf 2). Opening it in Excel shows…',
      opts: ['A date like 2-Jan', '1-2', '-1', '#VALUE!'], a: 'A date like 2-Jan' }
  ],

  wr1: [
    { id: 'w1-code', kind: 'formula', topic: 'Leading zeros', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW], ref: '=TEXT(C2,"0000")',
      q: 'ItemCode (column C) is a mess of numbers like <code>104</code> and text like <code>" 0402"</code>. In <b>RawOrders!S2</b>, turn it into a clean 4-character code like <b>0104</b>. It will be filled down to row 31.' },
    { id: 'w1-qty', kind: 'formula', topic: 'Text to numbers', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW], ref: '=IFERROR(VALUE(E2),"")',
      q: 'In <b>RawOrders!S2</b>, convert Qty (column E) to a <b>real number</b>, and show a <b>truly blank</b> result ("") when there is no usable number (blank, N/A, -, null). Filled down to row 31.' },
    { id: 'w1-store', kind: 'formula', topic: 'TRIM / UPPER', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW], ref: '=UPPER(TRIM(B2))',
      q: 'Store codes (column B) look like <code>" S02 "</code>, <code>s04</code>, <code>S01</code>. In <b>RawOrders!S2</b>, clean them to the form <b>S02</b>. Filled down to row 31.' },
    { id: 'w1-price', kind: 'formula', topic: 'Text to numbers', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW], ref: '=VALUE(F2)',
      q: 'UnitPrice (column F) holds things like <code>"$3.25"</code> and <code>"14.99 "</code>. In <b>RawOrders!S2</b>, turn it into a real number. Filled down to row 31.' },
    { id: 'w1-name', kind: 'formula', topic: 'TRIM / PROPER', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW], ref: '=PROPER(TRIM(G2))',
      q: 'In <b>RawOrders!S2</b>, clean Customer (column G): remove extra spaces and capitalize each word (<code>"  avery johnson "</code> → <b>Avery Johnson</b>). Filled down to row 31.' },
    { id: 'w1-blank', kind: 'formula', topic: 'Missing values', plat: 'xl365', book: 'wrangle', at: 'B2', show: [RAW], ref: '=COUNTBLANK(RawOrders!E2:E31)',
      q: 'Write a formula that counts the Qty cells (E2:E31) that are <b>completely empty</b>.' },
    { id: 'w1-fake', kind: 'formula', topic: 'Missing values', plat: 'xl365', book: 'wrangle', at: 'B2', show: [RAW], ref: '=COUNTIF(RawOrders!E2:E31,"N/A")+COUNTIF(RawOrders!E2:E31,"-")+COUNTIF(RawOrders!E2:E31,"null")',
      q: 'Write a formula that counts the Qty cells (E2:E31) holding a <b>fake-null word</b>: <code>N/A</code>, <code>-</code> or <code>null</code>.' },
    { id: 'w1-euro', kind: 'formula', topic: 'Dates', plat: 'xl365', book: 'wrangle', at: 'B2', same: true, show: [RAW], ref: '=DATE(RIGHT(RawOrders!D19,4),MID(RawOrders!D19,4,2),LEFT(RawOrders!D19,2))',
      q: 'RawOrders!D19 holds the European date text <code>03.09.2026</code> (day.month.year = 3 September 2026). Write a formula that builds a <b>real date</b> from that cell\'s text.' },
    { id: 'w1-zeros', kind: 'mc', topic: 'Leading zeros', q: 'Why does it matter that item code <code>0104</code> became the number <code>104</code>?',
      opts: ['Lookups against the text code "0104" will not match', 'Numbers take more memory', '104 is a different product', 'It does not matter'], a: 'Lookups against the text code "0104" will not match' },
    { id: 'w1-nulls', kind: 'mc', topic: 'Missing values', q: 'Which of these is a <b>fake null</b> that should be cleaned into a real blank?',
      opts: ['"N/A"', '0.5', '"S02"', '"0104"'], a: '"N/A"' },
    { id: 'w1-trim', kind: 'text', topic: 'TRIM / UPPER', q: 'What does <code>=UPPER(TRIM("  s02 "))</code> return?', a: ['S02'] },
    { id: 'w1-sumtext', kind: 'mc', topic: 'Text to numbers', q: 'E2 holds the TEXT "12" and E3 holds the number 8. What does <code>=SUM(E2:E3)</code> return?',
      opts: ['8', '20', '#VALUE!', '128'], a: '8' },
    { id: 'w1-zero', kind: 'mc', topic: 'Missing values', q: 'Why not just replace every missing quantity with 0 before training an AI model?',
      opts: ['The model learns that orders are smaller than they really are', 'Zero is not a number', 'AI models cannot read 0', 'It makes the file too big'], a: 'The model learns that orders are smaller than they really are' },
    { id: 'w1-text', kind: 'text', topic: 'Leading zeros', q: 'What does <code>=TEXT(7, "000")</code> return?', a: ['007'] },
    { id: 'w1-isnum', kind: 'mc', topic: 'Text to numbers', q: 'What does <code>=ISNUMBER("12")</code> return?',
      opts: ['FALSE', 'TRUE', '12', '#VALUE!'], a: 'FALSE' }
  ],

  wr2: [
    { id: 'w2-vlookup', kind: 'formula', topic: 'VLOOKUP', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW, IC], ref: '=VLOOKUP(TEXT(C2,"0000"),ItemCodes!$A$2:$D$25,2,FALSE)',
      q: 'In <b>RawOrders!S2</b>, look up the <b>Product name</b> for the row\'s ItemCode (column C) in <b>ItemCodes!A2:D25</b> (codes there are text like <code>0104</code>). Every row must find its product. Filled down to row 31.' },
    { id: 'w2-hlookup', kind: 'formula', topic: 'HLOOKUP', plat: 'xl365', book: 'wrangle', at: 'B2', show: [T], ref: '=HLOOKUP("S03",Targets!A1:F3,3,FALSE)',
      q: 'The Targets sheet runs <b>sideways</b> (stores across row 1). Write a formula that returns the <b>Sept Target for store S03</b>.' },
    { id: 'w2-region', kind: 'formula', topic: 'HLOOKUP', plat: 'xl365', book: 'wrangle', sheet: 'RawOrders', at: 'S2', fill: 31, show: [RAW, T], ref: '=HLOOKUP(UPPER(TRIM(B2)),Targets!$B$1:$F$2,2,FALSE)',
      q: 'In <b>RawOrders!S2</b>, return the <b>Region</b> (Targets row 2) for the row\'s store — note the store codes in column B are messy. Filled down to row 31.' },
    { id: 'w2-lastfirst', kind: 'formula', topic: 'Concatenation', plat: 'xl365', book: 'wrangle', sheet: 'Contacts', at: 'G2', fill: 9, show: [CT], ref: '=B2&", "&A2',
      q: 'In <b>Contacts!G2</b>, build <b>Last, First</b> (like <code>Whitfield, Dana</code>). Filled down to row 9.' },
    { id: 'w2-address', kind: 'formula', topic: 'Concatenation', plat: 'xl365', book: 'wrangle', sheet: 'Contacts', at: 'G2', fill: 9, show: [CT], ref: '=C2&", "&D2&" "&TEXT(E2,"00000")',
      q: 'In <b>Contacts!G2</b>, build an address line like <code>Cumming, GA 30040</code> — Zip codes must always show <b>5 digits</b>. Filled down to row 9.' },
    { id: 'w2-textjoin', kind: 'formula', topic: 'TEXTJOIN', plat: 'xl365', book: 'wrangle', at: 'B2', show: [CT], ref: '=TEXTJOIN(", ",TRUE,Contacts!A2:A9)',
      q: 'Write ONE formula that joins all first names in <b>Contacts!A2:A9</b> into one cell, separated by a comma and a space.' },
    { id: 'w2-filter', kind: 'formula', topic: 'FILTER', plat: 'xl365', book: 'wrangle', at: 'B2', show: [RAW], ref: '=FILTER(RawOrders!A2:A31,ISNUMBER(RawOrders!E2:E31))',
      q: 'Write ONE formula that spills the <b>OrderIDs whose Qty (column E) is already a real number</b>.' },
    { id: 'w2-tags', kind: 'formula', topic: 'Delimiters', plat: 'xl365', book: 'wrangle', sheet: 'Contacts', at: 'G2', fill: 9, show: [CT], ref: '=IF(F2="",0,LEN(F2)-LEN(SUBSTITUTE(F2,"|",""))+1)',
      q: 'Tags (column F) are separated by <code>|</code>, like <code>snacks|drinks</code>. In <b>Contacts!G2</b>, count the <b>number of tags</b> (0 when empty). Filled down to row 9.' },
    { id: 'w2-na', kind: 'mc', topic: 'Why lookups fail', q: '<code>=VLOOKUP(C2, ItemCodes!A2:D25, 2, FALSE)</code> shows <code>#N/A</code> when C2 is the number 104 and the table has "0104". Why?',
      opts: ['The number 104 and the text "0104" are different values', 'VLOOKUP cannot read numbers', 'The column number is wrong', 'The table must be sorted'], a: 'The number 104 and the text "0104" are different values' },
    { id: 'w2-hrow', kind: 'mc', topic: 'HLOOKUP', q: 'Where does HLOOKUP search for the key?',
      opts: ['Across the first row of the table', 'Down the first column', 'In every cell', 'In the last row'], a: 'Across the first row of the table' },
    { id: 'w2-tj', kind: 'text', topic: 'TEXTJOIN', q: 'What does <code>=TEXTJOIN("-", TRUE, "a", "", "b")</code> return?', a: ['a-b'] },
    { id: 'w2-colnum', kind: 'mc', topic: 'VLOOKUP', q: 'In <code>=VLOOKUP(key, ItemCodes!A2:D25, 4, FALSE)</code>, which column is returned?',
      opts: ['Column D (the 4th column of the table)', 'Column 4 of the whole sheet only if the table starts in A', 'The 4th matching row', 'Column E'], a: 'Column D (the 4th column of the table)' },
    { id: 'w2-delim', kind: 'mc', topic: 'Delimiters', q: 'What is a delimiter?',
      opts: ['A character that separates values, like , or | or a tab', 'A function that removes spaces', 'A type of number format', 'The header row'], a: 'A character that separates values, like , or | or a tab' },
    { id: 'w2-dollar', kind: 'mc', topic: 'Absolute references', q: 'Why write <code>ItemCodes!$A$2:$D$25</code> (with $) in a VLOOKUP you will fill down?',
      opts: ['So the lookup table does not shift as the formula moves down', 'To format the result as money', 'Because VLOOKUP requires $', 'To make it faster'], a: 'So the lookup table does not shift as the formula moves down' },
    { id: 'w2-pad', kind: 'text', topic: 'Concatenation', q: 'What does <code>="S" &amp; TEXT(3, "00")</code> return?', a: ['S03'] }
  ],

  sql: [
    { id: 's-where', kind: 'sql', topic: 'WHERE', show: ['products'], ref: "SELECT product, price FROM products WHERE category = 'Electronics';",
      q: 'List the <b>product and price</b> of every product in the <b>Electronics</b> category.' },
    { id: 's-top3', kind: 'sql', topic: 'ORDER BY / LIMIT', ordered: true, show: ['products'], ref: 'SELECT product, price FROM products ORDER BY price DESC LIMIT 3;',
      q: 'List the <b>product and price of the 3 most expensive products</b>, most expensive first.' },
    { id: 's-group', kind: 'sql', topic: 'GROUP BY', show: ['sales'], ref: 'SELECT store_id, SUM(qty) FROM sales GROUP BY store_id;',
      q: 'For each <b>store_id</b>, show the <b>total qty</b> sold (two columns: store_id, total).' },
    { id: 's-join', kind: 'sql', topic: 'JOIN', show: ['sales', 'products'], ref: "SELECT s.order_id, p.product FROM sales s JOIN products p ON s.sku = p.sku WHERE s.store_id = 'S05';",
      q: 'For every sale at store <b>S05</b>, show the <b>order_id and the product name</b> (two columns).' },
    { id: 's-having', kind: 'sql', topic: 'HAVING', show: ['products'], ref: 'SELECT category, COUNT(*) FROM products GROUP BY category HAVING COUNT(*) > 4;',
      q: 'Show each <b>category with more than 4 products</b> and its product count (two columns).' },
    { id: 's-avg', kind: 'sql', topic: 'Aggregates', show: ['sales'], ref: 'SELECT AVG(qty) FROM sales;',
      q: 'Show the <b>average qty</b> per sale (one value).' },
    { id: 's-city', kind: 'sql', topic: 'JOIN', ordered: true, show: ['sales', 'stores', 'products'], ref: 'SELECT st.city, SUM(s.qty * p.price) AS revenue FROM sales s JOIN stores st ON s.store_id = st.store_id JOIN products p ON s.sku = p.sku GROUP BY st.city ORDER BY revenue DESC;',
      q: 'Show each <b>city</b> and its <b>revenue</b> (qty × price), highest revenue first (two columns).' },
    { id: 's-low', kind: 'sql', topic: 'WHERE', show: ['products'], ref: 'SELECT sku FROM products WHERE in_stock < reorder_at;',
      q: 'List the <b>sku</b> of every product whose <b>in_stock is below its reorder_at</b>.' },
    { id: 's-intdiv', kind: 'mc', topic: 'Integer division', q: 'In SQLite, what is <code>SELECT 7 / 2;</code>?',
      opts: ['3', '3.5', '4', 'An error'], a: '3' },
    { id: 's-null', kind: 'mc', topic: 'NULL', q: 'Which WHERE clause finds rows where qty is missing?',
      opts: ['WHERE qty IS NULL', 'WHERE qty = NULL', "WHERE qty = ''", 'WHERE qty = 0'], a: 'WHERE qty IS NULL' },
    { id: 's-nowhere', kind: 'mc', topic: 'UPDATE safely', q: 'What does <code>UPDATE products SET price = 0;</code> do?',
      opts: ['Sets the price of EVERY product to 0', 'Nothing — WHERE is required', 'Sets only the first product', 'Shows an error'], a: 'Sets the price of EVERY product to 0' },
    { id: 's-having2', kind: 'mc', topic: 'HAVING', q: 'What is the difference between WHERE and HAVING?',
      opts: ['WHERE filters rows before grouping; HAVING filters groups after', 'They are the same', 'HAVING only works with text', 'WHERE only works with JOIN'], a: 'WHERE filters rows before grouping; HAVING filters groups after' },
    { id: 's-count', kind: 'text', topic: 'Aggregates', q: 'The products table has one row per product and there are 24 products. What does <code>SELECT COUNT(*) FROM products;</code> return?', a: ['24'] },
    { id: 's-joinlike', kind: 'mc', topic: 'JOIN', q: 'Which spreadsheet idea is most like a SQL JOIN?',
      opts: ['A VLOOKUP/XLOOKUP for every row', 'SUM', 'Sorting', 'Conditional formatting'], a: 'A VLOOKUP/XLOOKUP for every row' },
    { id: 's-quotes', kind: 'mc', topic: 'Syntax', q: 'How is a text value written in standard SQL?',
      opts: ["'Snacks' (single quotes)", '"Snacks" (double quotes)', 'Snacks (no quotes)', '[Snacks]'], a: "'Snacks' (single quotes)" }
  ],

  compare: [
    { id: 'cm-xl2013', kind: 'formula', topic: 'Translation', plat: 'xl2013', at: 'B2', show: [P], ref: '=INDEX(Products!B2:B25,MATCH("SKU-502",Products!A2:A25,0))',
      q: 'Translate <code>=XLOOKUP("SKU-502",Products!A2:A25,Products!B2:B25)</code> so it works in <b>Excel 2013</b>.' },
    { id: 'cm-gssort', kind: 'formula', topic: 'Silent differences', plat: 'gs', at: 'B2', show: [P], ref: '=SORT(Products!B2:D25,3,FALSE)',
      q: 'Excel 365\'s <code>=SORT(Products!B2:D25,3,-1)</code> sorts by price, highest first. Write the version that does the same in <b>Google Sheets</b>.' },
    { id: 'cm-maxifs', kind: 'formula', topic: 'Translation', plat: 'xl2013', at: 'B2', cse: true, show: [P], ref: '=MAX(IF(Products!C2:C25="Electronics",Products!D2:D25))',
      q: 'Translate <code>=MAXIFS(Products!D2:D25,Products!C2:C25,"Electronics")</code> for <b>Excel 2013</b> (highest Electronics price).' },
    { id: 'cm-concat', kind: 'formula', topic: 'Translation', plat: 'gs', sheet: 'Stores', at: 'G2', fill: 6, show: [ST], ref: '=B2&", "&C2',
      q: 'Excel 365\'s <code>=CONCAT(B2,", ",C2)</code> breaks in Google Sheets. In <b>Stores!G2</b>, write a Sheets version (like <code>Cumming, GA</code>). Filled down to row 6.' },
    { id: 'cm-ifs', kind: 'formula', topic: 'Translation', plat: 'xl2013', sheet: 'Products', at: 'J2', fill: 25, show: [P], ref: '=IF(D2>=10,"High",IF(D2>=3,"Mid","Low"))',
      q: 'Translate <code>=IFS(D2&gt;=10,"High",D2&gt;=3,"Mid",TRUE,"Low")</code> for <b>Excel 2013</b>, in <b>Products!J2</b>. Filled down to row 25.' },
    { id: 'cm-sql', kind: 'sql', topic: 'Spreadsheet → SQL', show: ['sales'], ref: "SELECT SUM(qty) FROM sales WHERE store_id = 'S01';",
      q: 'Write the SQL version of <code>=SUMIF(Sales!C2:C61,"S01",Sales!E2:E61)</code> (one value).' },
    { id: 'cm-everywhere', kind: 'mc', topic: 'Compatibility', q: 'Which function works the same in Excel 365, Excel 2013 AND Google Sheets?',
      opts: ['SUMIF', 'XLOOKUP', 'TEXTJOIN', 'LET'], a: 'SUMIF' },
    { id: 'cm-silent', kind: 'mc', topic: 'Silent differences', q: 'Why is a "silent difference" between apps more dangerous than an error?',
      opts: ['You get a wrong answer and nothing warns you', 'It crashes the app', 'It deletes the file', 'It only happens on phones'], a: 'You get a wrong answer and nothing warns you' },
    { id: 'cm-errors', kind: 'mc', topic: 'Errors', q: 'You type a broken formula. What do Excel and Google Sheets do?',
      opts: ['Excel refuses it with a pop-up; Sheets accepts it and shows #ERROR!', 'Both show #ERROR!', 'Both show a pop-up', 'Excel shows #ERROR!; Sheets shows a pop-up'], a: 'Excel refuses it with a pop-up; Sheets accepts it and shows #ERROR!' },
    { id: 'cm-groupby', kind: 'mc', topic: 'Spreadsheet → SQL', q: 'SQL\'s <code>GROUP BY store_id</code> with <code>SUM(qty)</code> is most like…',
      opts: ['A SUMIF for every store at once', 'A VLOOKUP', 'Sorting by store', 'Deleting duplicates'], a: 'A SUMIF for every store at once' },
    { id: 'cm-hash', kind: 'mc', topic: 'Compatibility', q: 'Where does the spill reference <code>B2#</code> work?',
      opts: ['Only in Excel 365', 'Excel 365 and Excel 2013', 'Google Sheets only', 'All three'], a: 'Only in Excel 365' },
    { id: 'cm-share', kind: 'mc', topic: 'Compatibility', q: 'You must share a lookup with people who might use Excel 2013 or Google Sheets. Which is safest?',
      opts: ['INDEX + MATCH', 'XLOOKUP', 'FILTER', 'LET'], a: 'INDEX + MATCH' },
    { id: 'cm-unique', kind: 'text', topic: 'Compatibility', q: 'What does Excel 2013 show for <code>=UNIQUE(C2:C25)</code>?', a: ['#NAME?', '#name'] }
  ],

  ml: [
    { id: 'm-balance', kind: 'sql', topic: 'Class balance', show: ['ml_examples'], ref: 'SELECT stockout, COUNT(*) FROM ml_examples GROUP BY stockout;',
      q: 'Show <b>how many examples have each stockout value</b> (two columns: stockout, count).' },
    { id: 'm-nulls', kind: 'sql', topic: 'Missing values', show: ['ml_examples'], ref: 'SELECT COUNT(*) FROM ml_examples WHERE units_last_week IS NULL;',
      q: 'Count the examples whose <b>units_last_week is missing</b> (one value).' },
    { id: 'm-split', kind: 'sql', topic: 'Train/test split', show: ['ml_examples'], ref: 'SELECT split, COUNT(*) FROM ml_examples GROUP BY split;',
      q: 'Show <b>how many examples are in each split</b> (two columns: split, count).' },
    { id: 'm-leak', kind: 'sql', topic: 'Data leakage', show: ['ml_examples'], ref: 'SELECT week, store_id, sku FROM ml_examples GROUP BY week, store_id, sku HAVING COUNT(DISTINCT split) > 1;',
      q: 'List the <b>week, store_id and sku</b> of every combination that appears in <b>both</b> the train and the test split (three columns).' },
    { id: 'm-acc', kind: 'sql', topic: 'Accuracy', show: ['predictions', 'ml_examples'], ref: 'SELECT AVG(p.predicted = e.stockout) FROM predictions p JOIN ml_examples e ON p.example_id = e.example_id;',
      q: 'Return the model\'s <b>accuracy</b> on the test rows as a <b>fraction between 0 and 1</b> (one value). The model\'s guesses are in <code>predictions</code>.' },
    { id: 'm-confusion', kind: 'sql', topic: 'Confusion matrix', show: ['predictions', 'ml_examples'], ref: 'SELECT e.stockout, p.predicted, COUNT(*) FROM predictions p JOIN ml_examples e ON p.example_id = e.example_id GROUP BY e.stockout, p.predicted;',
      q: 'Build the <b>confusion matrix</b>: one row per (real stockout, predicted) pair that occurs, with its count (three columns).' },
    { id: 'm-trainavg', kind: 'sql', topic: 'Missing values', show: ['ml_examples'], ref: "SELECT AVG(units_last_week) FROM ml_examples WHERE split = 'train';",
      q: 'Return the <b>average units_last_week of the training rows</b>, skipping missing values (one value).' },
    { id: 'm-fill', kind: 'sql', topic: 'Missing values', show: ['ml_examples'], ref: 'SELECT example_id, COALESCE(units_last_week, 0) FROM ml_examples;',
      q: 'List every <b>example_id</b> with its <b>units_last_week, using 0 where the value is missing</b> (two columns).' },
    { id: 'm-rate', kind: 'sql', topic: 'Class balance', show: ['ml_examples'], ref: "SELECT AVG(stockout) FROM ml_examples WHERE split = 'train';",
      q: 'Return the <b>fraction of training examples that are stockouts</b> (a number between 0 and 1).' },
    { id: 'm-trainset', kind: 'probe', topic: 'Feature tables', ref: "CREATE TABLE train_set AS SELECT e.example_id, e.promo, e.price, e.units_last_week, e.in_stock_start, p.category, e.stockout FROM ml_examples e JOIN products p ON e.sku = p.sku WHERE e.split = 'train';",
      probes: ['SELECT COUNT(*) FROM train_set;', 'SELECT restock_after FROM train_set;', 'SELECT COUNT(DISTINCT category) FROM train_set;', 'SELECT SUM(stockout) FROM train_set;', 'SELECT COUNT(*) FROM train_set WHERE category IS NULL;'],
      q: 'Create a table <b>train_set</b> holding only the <b>training</b> rows, <b>without</b> restock_after, keeping the label <b>stockout</b>, and with each product\'s <b>category</b> joined in from products.' },
    { id: 'm-label', kind: 'mc', topic: 'Features and labels', q: 'In a machine-learning table, what is the <b>label</b>?',
      opts: ['The answer the model is trying to predict', 'The name of the table', 'Any text column', 'The primary key'], a: 'The answer the model is trying to predict' },
    { id: 'm-id', kind: 'mc', topic: 'Features and labels', q: 'Why should <code>example_id</code> NOT be used as a feature?',
      opts: ['It is just a row number and says nothing about the real world', 'It is too large', 'It is a foreign key', 'Integers cannot be features'], a: 'It is just a row number and says nothing about the real world' },
    { id: 'm-target', kind: 'mc', topic: 'Data leakage', q: 'A model that uses <code>restock_after</code> scores 100% in testing but fails in real life. Why?',
      opts: ['restock_after is only known after the stockout happens — target leakage', 'The test set was too small', 'The model needed more features', 'restock_after has missing values'], a: 'restock_after is only known after the stockout happens — target leakage' },
    { id: 'm-dupes', kind: 'mc', topic: 'Data leakage', q: 'Some test rows are copies of training rows. What happens to the test score?',
      opts: ['It looks better than the model really is', 'It looks worse than the model really is', 'Nothing changes', 'The database refuses to run'], a: 'It looks better than the model really is' },
    { id: 'm-paradox', kind: 'mc', topic: 'Baselines', q: 'Only 1 in 6 test rows is a stockout. A model that ALWAYS predicts "no stockout" gets about 83% accuracy. Is it useful?',
      opts: ['No — it never catches a single stockout', 'Yes — 83% is a B', 'Yes — it is never wrong about non-stockouts, so it is perfect', 'It depends on the computer'], a: 'No — it never catches a single stockout' },
    { id: 'm-fn', kind: 'mc', topic: 'Confusion matrix', q: 'The real stockout was 1, but the model predicted 0. What kind of mistake is that?',
      opts: ['A false negative (a missed stockout)', 'A false positive (a false alarm)', 'A true negative', 'A true positive'], a: 'A false negative (a missed stockout)' },
    { id: 'm-time', kind: 'mc', topic: 'Train/test split', q: 'Why are weeks 1–4 used for training and weeks 5–6 for testing, instead of mixing all weeks?',
      opts: ['A real model predicts the future, so it should be tested on later weeks it never saw', 'Later weeks have more rows', 'SQL can only sort by week', 'It makes the label balanced'], a: 'A real model predicts the future, so it should be tested on later weeks it never saw' },
    { id: 'm-acc18', kind: 'text', topic: 'Accuracy', q: 'A model is right on 18 of 24 test rows. What is its accuracy, in percent? (number only)', a: ['75', '75%'] }
  ],

  rdbms: [
    { id: 'r-clubs', kind: 'probe', topic: 'Primary keys / NOT NULL', ref: 'CREATE TABLE clubs (club_id INTEGER PRIMARY KEY, name TEXT NOT NULL);',
      probes: ["INSERT INTO clubs (name) VALUES ('Chess');", 'INSERT INTO clubs (name) VALUES (NULL);', "INSERT INTO clubs (club_id, name) VALUES (1, 'Again');", "INSERT INTO clubs (club_id, name) VALUES (7, 'Robotics');", 'SELECT club_id, name FROM clubs ORDER BY club_id;'],
      q: 'Create a table <b>clubs</b> with <b>club_id</b> (a whole-number primary key the database fills in automatically) and <b>name</b> (text that can never be missing).' },
    { id: 'r-members', kind: 'probe', topic: 'Foreign keys', ref: 'CREATE TABLE clubs (club_id INTEGER PRIMARY KEY, name TEXT); CREATE TABLE members (member_id INTEGER PRIMARY KEY, name TEXT, club_id INTEGER REFERENCES clubs(club_id));',
      probes: ["INSERT INTO clubs (club_id, name) VALUES (1, 'Chess');", "INSERT INTO members (member_id, name, club_id) VALUES (10, 'Ana', 1);", "INSERT INTO members (member_id, name, club_id) VALUES (11, 'Ben', 99);", 'DELETE FROM clubs WHERE club_id = 1;', 'SELECT COUNT(*) FROM members;'],
      q: 'Create two tables: <b>clubs</b> (club_id INTEGER primary key, name TEXT) and <b>members</b> (member_id INTEGER primary key, name TEXT, club_id) — where a member\'s <b>club_id must point to a club that exists</b>.' },
    { id: 'r-check', kind: 'probe', topic: 'CHECK constraints', ref: 'CREATE TABLE grades (student TEXT NOT NULL, score INTEGER CHECK (score >= 0 AND score <= 100));',
      probes: ["INSERT INTO grades VALUES ('A', 95);", "INSERT INTO grades VALUES ('B', 101);", "INSERT INTO grades VALUES ('C', -1);", 'INSERT INTO grades VALUES (NULL, 50);', "INSERT INTO grades VALUES ('D', 0);", "INSERT INTO grades VALUES ('E', 100);", 'SELECT COUNT(*) FROM grades;'],
      q: 'Create a table <b>grades</b> with <b>student</b> (text, never missing) and <b>score</b> (a whole number that must be <b>between 0 and 100</b>, inclusive).' },
    { id: 'r-unique', kind: 'probe', topic: 'UNIQUE', ref: 'CREATE TABLE accounts (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE);',
      probes: ["INSERT INTO accounts (email) VALUES ('a@school.org');", "INSERT INTO accounts (email) VALUES ('a@school.org');", 'INSERT INTO accounts (email) VALUES (NULL);', "INSERT INTO accounts (email) VALUES ('b@school.org');", 'SELECT COUNT(*) FROM accounts;'],
      q: 'Create a table <b>accounts</b> with <b>id</b> (INTEGER primary key) and <b>email</b> — text that is required and can <b>never be used twice</b>.' },
    { id: 'r-default', kind: 'probe', topic: 'DEFAULT', ref: "CREATE TABLE tickets (ticket_id INTEGER PRIMARY KEY, title TEXT NOT NULL, status TEXT DEFAULT 'open');",
      probes: ["INSERT INTO tickets (title) VALUES ('Printer jam');", "INSERT INTO tickets (title, status) VALUES ('Wifi', 'closed');", 'INSERT INTO tickets (status) VALUES (\'open\');', 'SELECT title, status FROM tickets ORDER BY ticket_id;'],
      q: 'Create a table <b>tickets</b>: <b>ticket_id</b> (INTEGER primary key), <b>title</b> (required text) and <b>status</b> (text that is <b>\'open\'</b> when nobody gives one).' },
    { id: 'r-tx', kind: 'probe', topic: 'Transactions', must: ['BEGIN', 'COMMIT'], ref: "BEGIN; UPDATE products SET price = price * 1.1 WHERE category = 'Snacks'; COMMIT;",
      probes: ['BEGIN;', 'ROLLBACK;', "SELECT sku, ROUND(price, 3) FROM products WHERE category = 'Snacks' ORDER BY sku;", "SELECT COUNT(*) FROM products WHERE category <> 'Snacks' AND price > 30;"],
      q: 'Raise the price of every <b>Snacks</b> product by <b>10%</b>, as <b>one transaction</b> (BEGIN … COMMIT) so the change is saved for good.' },
    { id: 'r-join', kind: 'sql', topic: 'Keys & JOIN', show: ['sales', 'stores'], ref: 'SELECT s.order_id, st.manager FROM sales s JOIN stores st ON s.store_id = st.store_id;',
      q: 'Use the foreign key <code>sales.store_id → stores.store_id</code> to list every <b>order_id with its store\'s manager</b> (two columns).' },
    { id: 'r-pk', kind: 'mc', topic: 'Primary keys', q: 'What is a primary key?',
      opts: ['A column whose value is different for every row, used as the row\'s ID', 'The first column of every table', 'A password for the database', 'A column that links to another table'], a: 'A column whose value is different for every row, used as the row\'s ID' },
    { id: 'r-fk', kind: 'mc', topic: 'Foreign keys', q: '<code>sales.sku</code> REFERENCES <code>products.sku</code>. What does the database do with a sale for SKU-999 (no such product)?',
      opts: ['Refuses the INSERT', 'Creates SKU-999 in products', 'Saves it with a warning', 'Changes it to NULL'], a: 'Refuses the INSERT' },
    { id: 'r-anomaly', kind: 'mc', topic: 'Normalization', q: 'A flat sheet repeats each product\'s price on every order row. Someone fixes the price on only one row. This is called…',
      opts: ['An update anomaly', 'A foreign key', 'A transaction', 'Normalization'], a: 'An update anomaly' },
    { id: 'r-atomic', kind: 'mc', topic: 'Transactions', q: 'Halfway through a money transfer inside BEGIN … COMMIT, the power fails. What happens?',
      opts: ['The unfinished transaction is undone — no money is lost', 'Half the transfer is saved', 'The database is destroyed', 'The money is doubled'], a: 'The unfinished transaction is undone — no money is lost' },
    { id: 'r-notdb', kind: 'mc', topic: 'What is an RDBMS', q: 'Which of these is NOT a relational database management system?',
      opts: ['A CSV file', 'PostgreSQL', 'MySQL', 'SQLite'], a: 'A CSV file' },
    { id: 'r-strict', kind: 'mc', topic: 'Data types', q: 'products.price is a REAL column in a STRICT table. What happens with <code>UPDATE products SET price = \'cheap\'</code>?',
      opts: ['The database refuses it', 'The price becomes 0', 'It is stored as text', 'Every price becomes "cheap"'], a: 'The database refuses it' },
    { id: 'r-norm', kind: 'mc', topic: 'Normalization', q: 'What does normalization mean?',
      opts: ['Store each fact once, in one place, and link to it with keys', 'Make all numbers between 0 and 1', 'Sort every table', 'Delete NULL values'], a: 'Store each fact once, in one place, and link to it with keys' },
    { id: 'r-rollback', kind: 'mc', topic: 'Transactions', q: 'After <code>BEGIN; DELETE FROM sales;</code> you run <code>ROLLBACK;</code>. How many sales rows are left (there were 60)?',
      opts: ['60', '0', '59', 'It depends on the computer'], a: '60' },
    { id: 'r-acid', kind: 'mc', topic: 'Transactions', q: 'In ACID, what does the <b>A (atomicity)</b> promise?',
      opts: ['All of a transaction\'s changes happen, or none do', 'Data is encrypted', 'Queries run fast', 'Tables have primary keys'], a: 'All of a transaction\'s changes happen, or none do' }
  ]
};
