// Teacher-only answer key. NOT included in the student app.
// Every entry is verified by tests/challenges.test.js, and build.js prints it in dist/teacher-guide.html.
// sheet: [[address (Sheet!A1 or Sheet!A1:A9 = fill down), input, 'cse'?], ...]
module.exports = {
  // Lesson 1 — Excel 365
  '365-sum': { sheet: [['Scratch!B2', '=SUM(Products!F2:F25)']] },
  '365-invvalue': { sheet: [['Scratch!B3', '=SUMPRODUCT(Products!D2:D25,Products!F2:F25)']], alt: '=SUM(Products!D2:D25*Products!F2:F25)' },
  '365-countif': { sheet: [['Scratch!B4', '=COUNTIF(Products!C2:C25,"School Supplies")']] },
  '365-sumif': { sheet: [['Scratch!B5', '=SUMIF(Sales!C2:C61,"S03",Sales!E2:E61)']] },
  '365-xlookup': { sheet: [['Scratch!A7', 'SKU-404'], ['Scratch!B7', '=XLOOKUP(A7,Products!A2:A25,Products!B2:B25)']] },
  '365-filter': { sheet: [['Scratch!D2', '=FILTER(Products!B2:B25,Products!C2:C25="Drinks")']] },
  '365-sortunique': { sheet: [['Scratch!F2', '=SORT(UNIQUE(Products!C2:C25))']] },
  '365-ifs': { sheet: [['Products!I1', 'Status'], ['Products!I2:I25', '=IFS(F2<G2,"Reorder",F2<G2*1.5,"Low",TRUE,"OK")']] },
  '365-let': { sheet: [['Scratch!B9', '=LET(p,XLOOKUP("SKU-502",Products!A2:A25,Products!D2:D25),c,XLOOKUP("SKU-502",Products!A2:A25,Products!E2:E25),(p-c)/p)']] },
  '365-revenue': { sheet: [['Sales!G1', 'Revenue'], ['Sales!G2:G61', '=E2*XLOOKUP(D2,Products!$A$2:$A$25,Products!$D$2:$D$25)']] },
  // Lesson 2 — Excel 2013
  '13-name': { sheet: [['Scratch!B2', '=XLOOKUP("SKU-101",Products!A2:A25,Products!B2:B25)']], note: 'The correct result is #NAME? — the point is to see it.' },
  '13-indexmatch': { sheet: [['Scratch!B3', '=INDEX(Products!B2:B25,MATCH("SKU-404",Products!A2:A25,0))']] },
  '13-vlookup': { sheet: [['Scratch!B4', '=VLOOKUP("Hoodie",Products!B2:D25,3,FALSE)']], note: 'Without FALSE the answer is $5.99 (wrong) — a great discussion point.' },
  '13-nestedif': { sheet: [['Products!I2:I25', '=IF(F2<G2,"Reorder",IF(F2<G2*1.5,"Low","OK"))']] },
  '13-iferror': { sheet: [['Scratch!A6', 'SKU-101'], ['Scratch!B6', '=IFERROR(VLOOKUP(A6,Products!A2:B25,2,FALSE),"Not found")']] },
  '13-cse': { sheet: [['Scratch!B7', '=MAX(IF(Products!C2:C25="Electronics",Products!D2:D25))', 'cse']], note: 'Confirm with Ctrl+Shift+Enter. Plain Enter gives a wrong answer.' },
  '13-concat': { sheet: [['Scratch!B8', '=Products!B2&" - "&TEXT(Products!D2,"$0.00")']] },
  '13-sumifs': { sheet: [['Scratch!B9', '=SUMIFS(Sales!E2:E61,Sales!C2:C61,"S02",Sales!D2:D61,"SKU-3*")']] },
  // Lesson 3 — Google Sheets
  'gs-filter1': { sheet: [['Scratch!B2', '=FILTER(Products!B2:B25,Products!C2:C25="Apparel")']] },
  'gs-filter2': { sheet: [['Scratch!D2', '=FILTER(Products!B2:B25,Products!C2:C25="Snacks",Products!D2:D25>1)']] },
  'gs-sort': { sheet: [['Scratch!F2', '=SORT(Products!B2:D25,3,FALSE)']] },
  'gs-arrayformula': { sheet: [['Products!I2', '=ARRAYFORMULA(D2:D25-E2:E25)']] },
  'gs-query': { sheet: [['Scratch!J2', '=QUERY(Products!A1:H25,"select C, sum(F) group by C")']] },
  'gs-split': { sheet: [['Scratch!B10', '=SPLIT(Stores!E2," ")']] },
  'gs-open': { sheet: [['Scratch!B12', '=SUM(Sales!E2:E)']] },
  'gs-concat': { sheet: [['Scratch!B13', '=CONCATENATE(Stores!B2,", ",Stores!C2)']], alt: '=Stores!B2&", "&Stores!C2' },
  'gs-regex': { sheet: [['Scratch!B14', '=SUMPRODUCT(--REGEXMATCH(Products!B2:B25,"\\d"))']] },
  // Lesson 4 — CSV / TSV
  'csv-export': { csv: 'Export from spreadsheet ▸ Excel 365 ▸ Products ▸ CSV.' },
  'csv-fix-comma': { csv: 'In broken_products.csv change  Gel Pens, 4-pack  to  "Gel Pens, 4-pack"' },
  'csv-tsv': { csv: 'New file stores.tsv, paste stores.csv, Find & replace  ,  →  \\t  (Replace all).' },
  'csv-quote': { csv: 'Add to products.csv:  SKU-307,"12"" Ruler",School Supplies,1.99,0.6,30,10,Office Hub Supply' },
  // Lessons 5 & 6 — Data Wrangling Lab (Excel 365 or Google Sheets)
  'wr-code': { wr: [['RawOrders!I1', 'CleanCode'], ['RawOrders!I2:I31', '=TEXT(C2,"0000")']] },
  'wr-blanks': { wr: [['Report!B2', '=COUNTBLANK(RawOrders!E2:E31)']] },
  'wr-fakenull': { wr: [['Report!B3', '=COUNTIF(RawOrders!E2:E31,"N/A")+COUNTIF(RawOrders!E2:E31,"-")+COUNTIF(RawOrders!E2:E31,"null")']] },
  'wr-qty': { wr: [['RawOrders!J1', 'CleanQty'], ['RawOrders!J2:J31', '=IFERROR(VALUE(E2),"")']] },
  'wr-store': { wr: [['RawOrders!K1', 'CleanStore'], ['RawOrders!K2:K31', '=UPPER(TRIM(B2))']] },
  'wr-price': { wr: [['RawOrders!L1', 'CleanPrice'], ['RawOrders!L2:L31', '=VALUE(F2)']] },
  'wr-date': { wr: [['RawOrders!M1', 'CleanDate'], ['RawOrders!M2:M31', '=IF(ISNUMBER(D2),D2,DATEVALUE(D2))']], note: 'Row 19 (European date) shows #VALUE! here — that is the next challenge.' },
  'wr-euro': { wr: [['Report!B5', '=DATE(RIGHT(RawOrders!D19,4),MID(RawOrders!D19,4,2),LEFT(RawOrders!D19,2))']] },
  'wr-name': { wr: [['RawOrders!N1', 'CleanName'], ['RawOrders!N2:N31', '=IF(ISNUMBER(FIND(",",G2)),PROPER(TRIM(MID(G2,FIND(",",G2)+1,99)))&" "&LEFT(G2,FIND(",",G2)-1),PROPER(TRIM(G2)))']] },
  'wr-missing': { wr: [['Report!B4', '=COUNTBLANK(RawOrders!J2:J31)']], needs: ['wr-qty'] },
  'wr-vlookup': { wr: [['RawOrders!O1', 'Product'], ['RawOrders!O2:O31', '=VLOOKUP(I2,ItemCodes!$A$2:$D$25,2,FALSE)']], needs: ['wr-code'] },
  'wr-total': { wr: [['RawOrders!P1', 'LineTotal'], ['RawOrders!P2:P31', '=IF(J2="","",J2*XLOOKUP(I2,ItemCodes!$A$2:$A$25,ItemCodes!$D$2:$D$25))']], needs: ['wr-code', 'wr-qty'] },
  'wr-hlookup': { wr: [['Report!B7', '=HLOOKUP("S03",Targets!A1:F3,3,FALSE)']] },
  'wr-region': { wr: [['RawOrders!Q1', 'Region'], ['RawOrders!Q2:Q31', '=HLOOKUP(K2,Targets!$B$1:$F$2,2,FALSE)']], needs: ['wr-store'] },
  'wr-units': { wr: [['Report!B8', '=SUM(RawOrders!J2:J31)']], needs: ['wr-qty'] },
  'wr-lastfirst': { wr: [['Contacts!G2:G9', '=B2&", "&A2']] },
  'wr-mailing': { wr: [['Contacts!H2:H9', '=C2&", "&D2&" "&TEXT(E2,"00000")']] },
  'wr-tags': { wr: [['Contacts!I2:I9', '=IF(F2="",0,LEN(F2)-LEN(SUBSTITUTE(F2,"|",""))+1)']] },
  'wr-csvline': { wr: [['Report!B10', '=TEXTJOIN(",",FALSE,Contacts!A2:E2)']] },
  'wr-filter': { wr: [['Report!D2', '=FILTER(RawOrders!A2:A31,ISNUMBER(RawOrders!J2:J31)*(RawOrders!J2:J31>10))']], needs: ['wr-qty'] },
  // Lesson 7 — SQL
  'sql-star': { sql: 'SELECT * FROM products;' },
  'sql-where': { sql: "SELECT product, price FROM products WHERE category = 'Electronics';" },
  'sql-top3': { sql: 'SELECT product, price FROM products ORDER BY price DESC LIMIT 3;' },
  'sql-group': { sql: 'SELECT store_id, SUM(qty) FROM sales GROUP BY store_id;' },
  'sql-join': { sql: 'SELECT s.order_id, p.product FROM sales s JOIN products p ON s.sku = p.sku;' },
  'sql-having': { sql: 'SELECT category, COUNT(*) FROM products GROUP BY category HAVING COUNT(*) > 5;' },
  'sql-city': { sql: 'SELECT st.city, SUM(s.qty * p.price) AS revenue FROM sales s JOIN stores st ON s.store_id = st.store_id JOIN products p ON s.sku = p.sku GROUP BY st.city ORDER BY revenue DESC;' },
  'sql-avg': { sql: 'SELECT AVG(qty) FROM sales;', note: 'SUM(qty)/COUNT(*) gives 4 (integer division) — the trap.' },
  'sql-update': { sql: 'UPDATE products SET in_stock = reorder_at * 2 WHERE in_stock < reorder_at;' },
  // Lesson 9 — What is an RDBMS?  (rd: SQL run on the page's sandbox database; ui: clicks on the page)
  'rd-anomaly': { ui: 'Section 1: change only one of the highlighted Price cells in the flat sheet.' },
  'rd-no': { rd: ["INSERT INTO products VALUES ('SKU-101','Fake','Snacks',1,0.4,10,5,'X');", "INSERT INTO products (sku, category, price, in_stock) VALUES ('SKU-999','Snacks',1,5);", "UPDATE products SET price = -5 WHERE sku = 'SKU-101';"],
    note: 'Any 3 of the 6 "Try it" buttons in section 4 (UNIQUE, NOT NULL, CHECK, FOREIGN KEY, type).' },
  'rd-create': { rd: ['CREATE TABLE students (student_id INTEGER PRIMARY KEY, name TEXT NOT NULL);', "INSERT INTO students (name) VALUES ('Ana'), ('Ben');"] },
  'rd-fk-create': { rd: ['CREATE TABLE students (student_id INTEGER PRIMARY KEY, name TEXT NOT NULL);', "INSERT INTO students (name) VALUES ('Ana'), ('Ben');",
    'CREATE TABLE enrollments (student_id INTEGER REFERENCES students(student_id), course TEXT NOT NULL);', "INSERT INTO enrollments VALUES (1, 'Intro to AI');"], needsNote: 'Build students first (previous challenge).' },
  'rd-rollback': { rd: ['BEGIN; DELETE FROM sales; SELECT COUNT(*) FROM sales;', 'ROLLBACK;'] },
  'rd-bank': { ui: 'Section 5: With a transaction (BEGIN) → Step 1 → ⚡ Power failure! → With a transaction (BEGIN) → Step 1 → Step 2 → COMMIT.' }
};
